config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 # get 'contacts' => 'contacts#new'
  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'

  resource :contacts, only: [:new, :create], path_names: { :new => ''}
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
#class Contact < ActiveRecord::Base   это должно было бы быть... и тогда можно + валидацию:
	validates :email, presence: true
	validates :message, presence: true
#	vlaidate :message, presence: true :-)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
		
	def index
		@articles = Article.all
	end	
	def show
		@article = Article.find(params[:id])
	end	

	def new 
	end

	def create
		#render plain: params[:article].inspect
		@article = Article.new(article_params)
	
	if @article.valid?
		@article.save
		redirect_to @article
	else
		render action: 'new'
	end
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
		redirect_to @article
	else
		render action: 'edit'
	end
	end

	def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end
#	def destroy
#		@article = Article.find(params[:id])
#	
#		if @article.destroy(article_params)
#		redirect_to @article
#	else
#		render action: 'destroy'
#	end
#	end	
		
	private

	def article_params
		params.require(:article).permit(:title, :text)
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	
	def new
	end

	def create
		@contact = Contact.new(contact_params)
	#	@contact.save
	# ++ validation
	if @contact.valid?
		@contact.save
	else
		render action: 'new'
	end
	end	

	private

	def contact_params
		params.require(:contact).permit(:email, :message)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/home_index_controller.rb
class HomeIndexController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def terms
	end
	
	def about
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/home_index_helper.rb
module HomeIndexHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>
<%= form_for :article, url: article_path(@article), method: :put do |f| %>
<!-- '/articles' == articles_path -->
	<p>
		<%= f.label :title %><br />
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :text %><br />
		<%= f.text_area :text %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/articles/index.html.erb
<h1>List of articles</h1>
<% @articles.each do |article| %>
<h2>
	<%= article.title %>
</h2>

<p>
	<%= article.text %>
</p>
<p>
	<%= link_to 'Show', article_path(article) %> | 
	<%= link_to 'Edit', edit_article_path(article) %> |
	<%= link_to 'Destroy', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %>
	<li>

      <div class="ui checkbox">
        <input type="checkbox" data-id="<%= article.id %>"<%= article.title ? ' checked="checked"' : '' %>
        <p>Not complete</p>
      </div>

    </li>
    <li>

      <div class="ui checkbox">
        <input type="checkbox" data-id="<%= article.id %>"<%= article.title ? ' checked="checked"' : '' %>
        <p>Complete! ;-)</p>
      </div>

    </li>

</p>



<hr />
<% end %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= form_for :article, url: '/articles' do |f| %>
<!-- '/articles' == articles_path -->
	<p>
		<%= f.label :title %><br />
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :text %><br />
		<%= f.text_area :text %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>
	<%= @article.text %>
</p>

app/views/contacts/create.html.erb
<h1>Tanks!</h1>

app/views/contacts/new.html.erb
<h1>Contact us</h1>

<%= form_for :contact, url: contacts_path do |f| %>
<!-- '/articles' == articles_path -->
	<% if @contact && @contact.errors.any? %>
	<p>
		<ul>
			<% @contact.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</p>
	<% end %>
	<p>
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :message %><br />
		<%= f.text_area :message %>
	</p>

	<p>
		<%= f.submit 'Send message' %>
	</p>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>